### ISSUE TITLE
Undefined channel element: itunes:complete

### ISSUE THREAD

**Issue by Sideboard** [podlove/podlove-validator#6]
The Podlove Publisher offers a checkbox at Podlove>Podcast Settings>>Directory>>Podcast complete?, which inserts the element `<itunes:complete>yes</itunes:complete>` into the feed. The feed validation on the Podlove Dashboard fails with the message:

> Error: Undefined channel element: itunes:complete, line $NUM in Feed $FEED_TITLE.

Since the element is also described in https://github.com/podlove/podlove-validator/blob/master/docs/apple-podcast-spec.html I suppose it will be implemented at some point.

**Comment by timpritlove** [comment]
This is a bug in feedvalidator.

**Comment by timpritlove** [comment]
To clarify: this project (Podlove Validator) is still under development and is **not yet used** in Podlove Publisher. We use Feed Validator http://feedvalidator.org instead but we are not happy with it as it comes up with a lot of errors and warnings that aren't any.
